In [1]:
import numpy as np
from sklearn.model_selection import KFold

In [4]:
x= np.array([
    [1,2], [3,4], [1,2], [3,4]
    ])

y = np.array([1, 2, 3, 4])

In [5]:
x

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [6]:
y

array([1, 2, 3, 4])

In [7]:
kf = KFold(n_splits=2)

print(kf.get_n_splits(x))
print(kf)

2
KFold(n_splits=2, random_state=None, shuffle=False)


In [11]:
for train_idx, test_idx in kf.split(x):
    # print(train_idx)
    # print(test_idx)
    # print('='*5)
    print('---idx')
    print(train_idx, test_idx)
    print('---train data')
    print(x[train_idx])
    print('---validation data')
    print(x[test_idx])

---idx
[2 3] [0 1]
---train data
[[1 2]
 [3 4]]
---validation data
[[1 2]
 [3 4]]
---idx
[0 1] [2 3]
---train data
[[1 2]
 [3 4]]
---validation data
[[1 2]
 [3 4]]


In [ ]:
#### KFold

In [12]:
import pandas as pd

red_wine = pd.read_csv('winequality-red.csv', sep=';')
white_wine = pd.read_csv('winequality-white.csv', sep=';')
red_wine['color'] = 1
white_wine['color'] = 0

wine = pd.concat([red_wine, white_wine])

In [13]:
wine['taste'] = [1. if grade > 5 else 0 for grade in wine['quality']]

x = wine.drop(['taste','quality'], axis= 1)
y = wine['taste']

In [15]:
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=13)

wine_tree = DecisionTreeClassifier(max_depth=2, random_state=13)
wine_tree.fit(x_train, y_train)

y_pred_tr = wine_tree.predict(x_train)
y_pred_test = wine_tree.predict(x_test)

accuracy_score(y_train, y_pred_tr)
accuracy_score(y_test, y_pred_test)

print('Train Acc: ', accuracy_score(y_train, y_pred_tr))
print('Test Acc: ', accuracy_score(y_test, y_pred_test))

Train Acc:  0.7294593034442948
Test Acc:  0.7161538461538461


In [20]:

from sklearn.model_selection import KFold
kfold = KFold(n_splits=5)
wine_tree_cv = DecisionTreeClassifier(max_depth=2, random_state=13)


In [22]:
for train_idx, test_idx in kfold.split(x):
    print(len(train_idx),len(test_idx))

5197 1300
5197 1300
5198 1299
5198 1299
5198 1299


In [23]:
cv_accuracy = []

for train_idx, test_idx in kfold.split(x):
    x_train, x_test = x.iloc[train_idx], x.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
    wine_tree_cv.fit(x_train, y_train)
    pred = wine_tree_cv.predict(x_test)
    cv_accuracy.append(accuracy_score(y_test, pred))

cv_accuracy

[0.6007692307692307,
 0.6884615384615385,
 0.7090069284064665,
 0.7628945342571208,
 0.7867590454195535]

In [24]:
np.mean(cv_accuracy)

0.709578255462782

#### StratifiedKFold

In [27]:
from sklearn.model_selection import StratifiedKFold

skFold = StratifiedKFold(n_splits=5)
wine_tree_cv = DecisionTreeClassifier(max_depth=2, random_state=13)

cv_accuracy = []

for train_idx, test_idx in skFold.split(x,y):
    x_train, x_test = x.iloc[train_idx], x.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
    wine_tree_cv.fit(x_train, y_train)
    pred = wine_tree_cv.predict(x_test)
    cv_accuracy.append(accuracy_score(y_test, pred))

cv_accuracy

    

[0.5523076923076923,
 0.6884615384615385,
 0.7143956889915319,
 0.7321016166281755,
 0.7567359507313318]

In [28]:
np.mean(cv_accuracy)

0.6888004974240539

In [29]:
from sklearn.model_selection import cross_val_score

skfold =  StratifiedKFold(n_splits=5)
wine_tree_cv = DecisionTreeClassifier(max_depth=2, random_state=13)

cross_val_score(wine_tree_cv, x, y, scoring=None, cv=skfold)

array([0.55230769, 0.68846154, 0.71439569, 0.73210162, 0.75673595])

In [30]:
from sklearn.model_selection import cross_val_score

skfold =  StratifiedKFold(n_splits=5)
wine_tree_cv = DecisionTreeClassifier(max_depth=5, random_state=13)

cross_val_score(wine_tree_cv, x, y, scoring=None, cv=skfold)

array([0.50076923, 0.62615385, 0.69745958, 0.7582756 , 0.74903772])

In [35]:
def skfold_dt(depth):
    skfold =  StratifiedKFold(n_splits=5)
    wine_tree_cv = DecisionTreeClassifier(max_depth=depth, random_state=13)

    print(cross_val_score(wine_tree_cv, x, y, scoring=None, cv=skfold))

In [36]:
skfold_dt(3)

[0.56846154 0.68846154 0.71439569 0.73210162 0.75673595]


In [39]:
from sklearn.model_selection import cross_validate

cross_validate(wine_tree_cv, x, y, cv=skfold, return_train_score=True)

{'fit_time': array([0.03060651, 0.03144884, 0.0311265 , 0.03205824, 0.0325191 ]),
 'score_time': array([0.00208139, 0.00200033, 0.00214076, 0.00149488, 0.00100017]),
 'test_score': array([0.51615385, 0.60076923, 0.66743649, 0.71054657, 0.72517321]),
 'train_score': array([0.87704445, 0.90475274, 0.89034244, 0.89726818, 0.88822624])}

In [40]:
red_wine = pd.read_csv('winequality-red.csv', sep=';')
white_wine = pd.read_csv('winequality-white.csv', sep=';')
red_wine['color'] = 1
white_wine['color'] = 0

wine = pd.concat([red_wine, white_wine])

wine['taste'] = [1. if grade > 5 else 0 for grade in wine['quality']]

x = wine.drop(['taste','quality'], axis= 1)
y = wine['taste']

### GridSearchCV

In [43]:
from sklearn.model_selection import GridSearchCV

params = {'max_depth': [2, 4, 7, 10]}
wine_tree = DecisionTreeClassifier(max_depth=2, random_state=13)

# cv는 k-fold와 같은 의미
gridsearch = GridSearchCV(estimator=wine_tree, param_grid=params, cv= 5)
gridsearch.fit(x, y)

GridSearchCV(cv=5,
             estimator=DecisionTreeClassifier(max_depth=2, random_state=13),
             param_grid={'max_depth': [2, 4, 7, 10]})

In [44]:
import pprint

pp = pprint.PrettyPrinter(indent=4)
pp.pprint(gridsearch.cv_results_)

{   'mean_fit_time': array([0.00622358, 0.01010599, 0.02012391, 0.03010569]),
    'mean_score_time': array([0.00120115, 0.00155535, 0.00149288, 0.00179901]),
    'mean_test_score': array([0.6888005 , 0.66356523, 0.65340854, 0.64401587]),
    'param_max_depth': masked_array(data=[2, 4, 7, 10],
             mask=[False, False, False, False],
       fill_value='?',
            dtype=object),
    'params': [   {'max_depth': 2},
                  {'max_depth': 4},
                  {'max_depth': 7},
                  {'max_depth': 10}],
    'rank_test_score': array([1, 2, 3, 4]),
    'split0_test_score': array([0.55230769, 0.51230769, 0.50846154, 0.51615385]),
    'split1_test_score': array([0.68846154, 0.63153846, 0.60307692, 0.60076923]),
    'split2_test_score': array([0.71439569, 0.72363356, 0.68360277, 0.66743649]),
    'split3_test_score': array([0.73210162, 0.73210162, 0.73672055, 0.71054657]),
    'split4_test_score': array([0.75673595, 0.7182448 , 0.73518091, 0.72517321]),
    'std

In [45]:
gridsearch.best_estimator_

DecisionTreeClassifier(max_depth=2, random_state=13)

In [46]:
gridsearch.best_score_

0.6888004974240539

In [47]:
gridsearch.best_params_

{'max_depth': 2}

In [50]:
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler

estimators = [
    ('scaler', StandardScaler()),
    ('clf', DecisionTreeClassifier())
]

pipe = Pipeline(estimators)

In [52]:
param_grid = [ {'clf__max_depth': [2, 4, 7, 10]} ]
GridSearch = GridSearchCV(estimator=pipe, param_grid=param_grid, cv=5)
GridSearch.fit(x, y)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('clf',
                                        DecisionTreeClassifier(max_depth=2,
                                                               random_state=13))]),
             param_grid=[{'clf__max_depth': [2, 4, 7, 10]}])

In [53]:
GridSearch.best_score_

0.6888004974240539

In [54]:
score_df = pd.DataFrame(GridSearch.cv_results_)
score_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.007437      0.000682         0.001514        0.000444   
1       0.012398      0.000444         0.002073        0.000136   
2       0.022554      0.001580         0.001780        0.000395   
3       0.033345      0.001699         0.001602        0.000492   

  param_clf__max_depth                  params  split0_test_score  \
0                    2   {'clf__max_depth': 2}           0.552308   
1                    4   {'clf__max_depth': 4}           0.512308   
2                    7   {'clf__max_depth': 7}           0.508462   
3                   10  {'clf__max_depth': 10}           0.516154   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.688462           0.714396           0.732102           0.756736   
1           0.631538           0.723634           0.732102           0.718245   
2           0.604615           0.682063           0.736721           0.735181   
3           0.602308           0.665897           0.710547           0.725173   

   mean_test_score  std_test_score  rank_test_score  
0         0.688800        0.071799                1  
1         0.663565        0.083905                2  
2         0.653408        0.086993                3  
3         0.644016        0.076915                4

In [55]:
score_df[['params', 'rank_test_score', 'mean_test_score', 'std_test_score']]

params  rank_test_score  mean_test_score  std_test_score
0   {'clf__max_depth': 2}                1         0.688800        0.071799
1   {'clf__max_depth': 4}                2         0.663565        0.083905
2   {'clf__max_depth': 7}                3         0.653408        0.086993
3  {'clf__max_depth': 10}                4         0.644016        0.076915